// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/silver-surfer/app"
	"github.com/devtron-labs/silver-surfer/app/api"
	"github.com/devtron-labs/silver-surfer/app/logger"
)

// Injectors from Wire.go:

func InitializeApp() (*app.App, error) {
	sugaredLogger := logger.NewSugaredLogger()
	grpcHandlerImpl := api.NewGrpcHandlerImpl(sugaredLogger)
	appApp := app.NewApp(sugaredLogger, grpcHandlerImpl)
	return appApp, nil
}
