// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/devtron-labs/common-lib/utils/k8s"
	"github.com/devtron-labs/silver-surfer/app/api"
	"github.com/devtron-labs/silver-surfer/app/logger"
	"github.com/devtron-labs/silver-surfer/app/service"
)

// Injectors from Wire.go:

func InitializeApp() (*App, error) {
	sugaredLogger := logger.NewSugaredLogger()
	runtimeConfig, err := k8s.GetRuntimeConfig()
	if err != nil {
		return nil, err
	}
	k8sServiceImpl := k8s.NewK8sUtil(sugaredLogger, runtimeConfig)
	clusterUpgradeReadServiceImpl := service.NewClusterUpgradeReadServiceImpl(sugaredLogger, k8sServiceImpl)
	grpcHandlerImpl := api.NewGrpcHandlerImpl(sugaredLogger, clusterUpgradeReadServiceImpl)
	app := NewApp(sugaredLogger, grpcHandlerImpl)
	return app, nil
}
